# Generated by Django 3.2.2 on 2021-05-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.TextField(max_length=20)),
                ('covid_bed_total', models.IntegerField()),
                ('covid_bed_occupied', models.IntegerField()),
                ('covid_bed_vacant', models.IntegerField()),
                ('oxy_bed_total', models.IntegerField()),
                ('oxy_bed_occupied', models.IntegerField()),
                ('oxy_bed_vacant', models.IntegerField()),
                ('non_oxy_bed_total', models.IntegerField()),
                ('non_oxy_bed_occupied', models.IntegerField()),
                ('non_oxy_bed_vacant', models.IntegerField()),
                ('icu_bed_total', models.IntegerField()),
                ('icu_bed_occupied', models.IntegerField()),
                ('icu_bed_vacant', models.IntegerField()),
                ('vent_bed_total', models.IntegerField()),
                ('vent_bed_occupied', models.IntegerField()),
                ('vent_bed_vacant', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('contactnumber', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
