# Generated by Django 3.2.2 on 2021-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210510_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
