# Generated by Django 3.2.2 on 2021-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_applied_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
