# Generated by Django 3.2.2 on 2021-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_applied_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='tweeted',
            field=models.CharField(choices=[('0', 'tweeted'), ('1', 'nottweeted')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='applied',
            name='bed_type',
            field=models.CharField(choices=[('1', 'Covid Bed'), ('2', 'Oxygen Bed'), ('3', 'Non oxygen Bed'), ('4', 'ICU Bed'), ('5', 'Ventilator Bed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applied',
            name='status',
            field=models.CharField(choices=[('0', 'Visible'), ('1', 'Invisible')], default='0', max_length=1),
        ),
    ]
