# Generated by Django 3.2.2 on 2021-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hospitals_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='Hospital_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
