# Generated by Django 3.2.2 on 2021-05-17 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_hospitals_hospital_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('bed_type', models.CharField(choices=[(1, 'Covid Bed'), (2, 'Oxygen Bed'), (3, 'Non oxygen Bed'), (4, 'ICU Bed'), (5, 'Ventilator Bed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
