# Generated by Django 3.2.2 on 2021-05-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='status',
            field=models.CharField(choices=[(0, 'Visible'), (1, 'Invisible')], default=0, max_length=1),
        ),
    ]
