# Generated by Django 3.2.2 on 2021-05-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applied_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitals'),
        ),
    ]
