# Generated by Django 3.2.2 on 2021-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_applied_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='hospital',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
